### ISSUE TITLE
[Enhancement] Add support for Bluetooth Input selection

### ISSUE THREAD

**Issue by MwC-Trexx** [krauskopf/node-red-contrib-avr-yamaha#11]
Please add support for switching input to "Bluetooth"

**Comment by krauskopf** [comment]
Hi,
this should already work with the existing nodes, by using the following settings in the put node:
![grafik](https://user-images.githubusercontent.com/1938031/54638534-91e31a00-4a8b-11e9-8b0f-1c598754a655.png)
Unfortunately I cannot test, because my receiver does not support bluetooth.
Regards
Sebastian

**Comment by MwC-Trexx** [comment]
Thanks Sebastian.  I will give that a try.

**Comment by krauskopf** [comment]
Did you already give it a try? Is it working?
